In [1]:
import pandas as pd

ri = pd.read_csv('datasets/police.csv')
ri.info()
ri

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91741 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               91741 non-null  object
 1   stop_date           91741 non-null  object
 2   stop_time           91741 non-null  object
 3   county_name         0 non-null      float64
 4   driver_gender       86536 non-null  object
 5   driver_race         86539 non-null  object
 6   violation_raw       86539 non-null  object
 7   violation           86539 non-null  object
 8   search_conducted    91741 non-null  bool
 9   search_type         3307 non-null   object
 10  stop_outcome        86539 non-null  object
 11  is_arrested         86539 non-null  object
 12  stop_duration       86539 non-null  object
 13  drugs_related_stop  91741 non-null  bool
 14  district            91741 non-null  object
dtypes: bool(2), float64(1), object(12)
memory usage: 9.3+ MB

,state,stop_date,stop_time,county_name,driver_gender,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,district
0,RI,2005-01-04,12:55,NaN,M,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False,Zone X4
1,RI,2005-01-23,23:15,NaN,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
2,RI,2005-02-17,04:15,NaN,M,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X4
3,RI,2005-02-20,17:15,NaN,M,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False,Zone X1
4,RI,2005-02-24,01:20,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone X3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,RI,2015-12-31,21:21,NaN,F,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone K2
91737,RI,2015-12-31,21:59,NaN,F,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False,Zone K3
91738,RI,2015-12-31,22:04,NaN,M,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,0-15 Min,False,Zone X3
91739,RI,2015-12-31,22:09,NaN,F,Hispanic,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False,Zone K3
91740,RI,2015-12-31,22:47,NaN,M,White,Registration Violation,Registration/plates,False,NaN,Citation,False,0-15 Min,False,Zone X4

In [2]:
#Examining the dataset

#Throughout this course, you'll be analyzing a dataset of traffic stops in Rhode Island that was collected by the Stanford
#Open Policing Project.

#Before beginning your analysis, it's important that you familiarize yourself with the dataset. In this exercise, you'll
#read the dataset into pandas, examine the first few rows, and then count the number of missing values.

# Import the pandas library as pd
import pandas as pd

# Read 'police.csv' into a DataFrame named ri
ri = pd.read_csv('datasets/police.csv')

# Examine the head of the DataFrame
print(ri.head(), '\n')

# Count the number of missing values in each column
print(ri.isnull().sum())

  state   stop_date stop_time  county_name driver_gender driver_race  \
0    RI  2005-01-04     12:55          NaN             M       White
1    RI  2005-01-23     23:15          NaN             M       White
2    RI  2005-02-17     04:15          NaN             M       White
3    RI  2005-02-20     17:15          NaN             M       White
4    RI  2005-02-24     01:20          NaN             F       White

                    violation_raw  violation  search_conducted search_type  \
0  Equipment/Inspection Violation  Equipment             False         NaN
1                        Speeding   Speeding             False         NaN
2                        Speeding   Speeding             False         NaN
3                Call for Service      Other             False         NaN
4                        Speeding   Speeding             False         NaN

    stop_outcome is_arrested stop_duration  drugs_related_stop district
0       Citation       False      0-15 Min               False  Zone X4
1       Citation       False      0-15 Min               False  Zone K3
2       Citation       False      0-15 Min               False  Zone X4
3  Arrest Driver        True     16-30 Min               False  Zone X1
4       Citation       False      0-15 Min               False  Zone X3

state                     0
stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5205
driver_race            5202
violation_raw          5202
violation              5202
search_conducted          0
search_type           88434
stop_outcome           5202
is_arrested            5202
stop_duration          5202
drugs_related_stop        0
district                  0
dtype: int64

In [3]:
#Dropping columns

#Often, a DataFrame will contain columns that are not useful to your analysis. Such columns should be dropped from the
#DataFrame, to make it easier for you to focus on the remaining columns.

#In this exercise, you'll drop the county_name column because it only contains missing values, and you'll drop the state
#column because all of the traffic stops took place in one state (Rhode Island). Thus, these columns can be dropped because
#they contain no useful information. The number of missing values in each column has been printed to the console for you.

# Count the number of missing values in each column
print(ri.isnull().sum(), '\n')

# Examine the shape of the DataFrame
print(ri.shape, '\n')

# Drop the 'county_name' and 'state' columns
ri.drop(['county_name', 'state'], axis='columns', inplace=True)

# Examine the shape of the DataFrame (again)
print(ri.shape)

state                     0
stop_date                 0
stop_time                 0
county_name           91741
driver_gender          5205
driver_race            5202
violation_raw          5202
violation              5202
search_conducted          0
search_type           88434
stop_outcome           5202
is_arrested            5202
stop_duration          5202
drugs_related_stop        0
district                  0
dtype: int64

(91741, 15)

(91741, 13)

In [4]:
#Dropping rows

#When you know that a specific column will be critical to your analysis, and only a small fraction of rows are missing a
#value in that column, it often makes sense to remove those rows from the dataset.

#During this course, the driver_gender column will be critical to many of your analyses. Because only a small fraction of
#rows are missing driver_gender, we'll drop those rows from the dataset.

# Count the number of missing values in each column
print(ri.isnull().sum(), '\n')

# Drop all rows that are missing 'driver_gender'
ri.dropna(subset=['driver_gender'], inplace=True)

# Count the number of missing values in each column (again)
print(ri.isnull().sum(), '\n')

# Examine the shape of the DataFrame
print(ri.shape)

stop_date                 0
stop_time                 0
driver_gender          5205
driver_race            5202
violation_raw          5202
violation              5202
search_conducted          0
search_type           88434
stop_outcome           5202
is_arrested            5202
stop_duration          5202
drugs_related_stop        0
district                  0
dtype: int64

stop_date                 0
stop_time                 0
driver_gender             0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           83229
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
district                  0
dtype: int64

(86536, 13)

In [5]:
#Finding an incorrect data type

#The dtypes attribute of the ri DataFrame has been printed for you. Your task is to explore the ri DataFrame in the IPython
#Shell to determine which column's data type should be changed.

ri.dtypes

stop_date             object
stop_time             object
driver_gender         object
driver_race           object
violation_raw         object
violation             object
search_conducted        bool
search_type           object
stop_outcome          object
is_arrested           object
stop_duration         object
drugs_related_stop      bool
district              object
dtype: object

In [6]:
#Possible Answers

#stop_time should have a data type of float

#search_conducted should have a data type of object

#is_arrested should have a data type of bool*

#district should have a data type of int

In [7]:
#Fixing a data type

#We saw in the previous exercise that the is_arrested column currently has the object data type. In this exercise, we'll
#change the data type to bool, which is the most suitable type for a column containing True and False values.

#Fixing the data type will enable us to use mathematical operations on the is_arrested column that would not be possible
#otherwise.

# Examine the head of the 'is_arrested' column
print(ri.is_arrested.head(), '\n')

# Check the data type of 'is_arrested'
print(ri.is_arrested.dtype, '\n')

# Change the data type of 'is_arrested' to 'bool'
ri['is_arrested'] = ri.is_arrested.astype('bool')

# Check the data type of 'is_arrested' (again)
print(ri.is_arrested.dtype)

0    False
1    False
2    False
3     True
4    False
Name: is_arrested, dtype: object

object

bool

In [8]:
#Combining object columns

#Currently, the date and time of each traffic stop are stored in separate object columns: stop_date and stop_time.

#In this exercise, you'll combine these two columns into a single column, and then convert it to datetime format. This will
#enable convenient date-based attributes that we'll use later in the course.

# Concatenate 'stop_date' and 'stop_time' (separated by a space)
combined = ri.stop_date.str.cat(ri.stop_time, sep=' ')

# Convert 'combined' to datetime format
ri['stop_datetime'] = pd.to_datetime(combined)

# Examine the data types of the DataFrame
print(ri.dtypes)

stop_date                     object
stop_time                     object
driver_gender                 object
driver_race                   object
violation_raw                 object
violation                     object
search_conducted                bool
search_type                   object
stop_outcome                  object
is_arrested                     bool
stop_duration                 object
drugs_related_stop              bool
district                      object
stop_datetime         datetime64[ns]
dtype: object

In [9]:
#Setting the index

#The last step that you'll take in this chapter is to set the stop_datetime column as the DataFrame's index. By replacing
#the default index with a DatetimeIndex, you'll make it easier to analyze the dataset by date and time, which will come in
#handy later in the course!

# Set 'stop_datetime' as the index
ri.set_index('stop_datetime', inplace=True)

# Examine the index
print(ri.index, '\n')

# Examine the columns
print(ri.columns)

DatetimeIndex(['2005-01-04 12:55:00', '2005-01-23 23:15:00',
               '2005-02-17 04:15:00', '2005-02-20 17:15:00',
               '2005-02-24 01:20:00', '2005-03-14 10:00:00',
               '2005-03-29 21:55:00', '2005-04-04 21:25:00',
               '2005-07-14 11:20:00', '2005-07-14 19:55:00',
               ...
               '2015-12-31 13:23:00', '2015-12-31 18:59:00',
               '2015-12-31 19:13:00', '2015-12-31 20:20:00',
               '2015-12-31 20:50:00', '2015-12-31 21:21:00',
               '2015-12-31 21:59:00', '2015-12-31 22:04:00',
               '2015-12-31 22:09:00', '2015-12-31 22:47:00'],
              dtype='datetime64[ns]', name='stop_datetime', length=86536, freq=None)

Index(['stop_date', 'stop_time', 'driver_gender', 'driver_race',
       'violation_raw', 'violation', 'search_conducted', 'search_type',
       'stop_outcome', 'is_arrested', 'stop_duration', 'drugs_related_stop',
       'district'],
      dtype='object')